name: Build Check

on:
  push:
    branches:["main"]
  pulll_request:
    branches:["main"]

job:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: action/checkout@v4

    - name: Setup .NET
      uses: action/ setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ApexSound-BackEnd/ApexSound-BackEnd.csproj

    - name: Build
      run: dotnet build ApexSound-BackEnd/ApexSound-BackEnd.csproj --no-restore --configuration Release      
